# Generated by Django 6.0.4 on 2026-04-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Security', 'Security'), ('Soft Skills', 'Soft Skills'), ('Compliance', 'Compliance')], max_length=100)),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('SALES', 'Sales'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('instructor_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ENROLLED', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'session'), name='unique_employee_per_session')],
            },
        ),
    ]
